version: '3.8'

services:
  booking_api:
    container_name: booking_api
  postgres:
    image: ${DB_IMAGE}
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data

  organization_api:
    container_name: organization_api
    build:
      context: .
      dockerfile: booking_api/Dockerfile
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8000"

  nginx:
    image: nginx:1.21.6
    container_name: nginx
    volumes:
      - ./deploy/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./deploy/nginx/configs:/etc/nginx/conf.d:ro
    ports:
      - '80:80'
    depends_on:
      - booking_api

  redis:
    image: redis:6.2-alpine
    container_name: redis
    ports:
      - '6379'
#    volumes:
#      - ${HOST_PATH_REDIS}:/var/lib/redis/data

volumes:
  pgdata:
