version: '3.8'

services:
  iasurgg.postgres:
    image: ${DB_IMAGE}
    hostname: ${POSTGRES_HOST}
    container_name: ${POSTGRES_HOST}
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./docker/postgres_db:/var/lib/postgresql/data
    env_file:
      - ./.env
