version: '3.8'

services:
  api:
    container_name: booking_api
    build:
      context: .
      dockerfile: deploy/api.Dockerfile
    env_file:
      - .env
    depends_on:
      - postgres
    ports:
      - "8000"

  postgres:
    image: postgres:15
    container_name: booking_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data

  nginx:
    image: nginx:1.21.6
    container_name: booking_nginx
    volumes:
      - ./deploy/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./deploy/nginx/configs:/etc/nginx/conf.d:ro
    ports:
      - '80:80'
    depends_on:
      - api

  redis:
    image: redis:6.2-alpine
    container_name: booking_redis
    ports:
      - '6379'

volumes:
  pgdata:
