services:
  api:
    container_name: booking_api
    build:
      context: .
      dockerfile: deploy/api.Dockerfile
    env_file:
      - .env
    depends_on:
      - postgres
    ports:
      - "8000"

  postgres:
    image: postgres:15-alpine
    container_name: booking_postgres
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data

  nginx:
    image: nginx:1.23.3-alpine
    container_name: booking_nginx
    volumes:
      - ./deploy/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./deploy/nginx/configs:/etc/nginx/conf.d:ro
    ports:
      - '80:80'
    depends_on:
      - api

  redis:
    image: redis:7.0.8-alpine
    container_name: booking_redis

volumes:
  pgdata:
