@startuml
actor User
participant Auth
participant BookingService
participant AsyncAPI
participant Billing_STUB
queue BillingNotifications
database Storage

User -> BookingService ++: buy movie(s)

group User is not authenticated
    BookingService -> Auth: authentication
    Auth -> BookingService: Token
end

BookingService -> BookingService: user authorization
BookingService -> AsyncAPI ++: request for movie(s) data
return movie(s) data
BookingService -> Storage: create order
note left: order with \npending status

group Unnecessary
    BookingService -> Billing_STUB ++: redirect for payment
    Billing_STUB -> BookingService: payment_id
    Billing_STUB -> BillingNotifications --: notification with payment_id
    BillingNotifications -> BookingService: notification with payment_id
    BookingService -> Storage: order status update
end

BookingService -> Storage --: update order status

@enduml