@startuml
actor Host
participant Auth
participant BookingService as BillingService
participant AsyncAPI
participant NotificationService

database Storage

group Event CRUD operations by host [Событие просмотра фильма]
    Host -> BillingService ++: action

    group authentication routine
        BillingService -> Auth: ...
        Auth -> BillingService: ...
    end

    BillingService -> Storage: get current schedule

    group Create
        alt time slot is empty for chosen place
            BillingService -> Storage: get purchased films
            BillingService -> Storage: insert
            BillingService -> Host: OK

        else time slot is NOT empty for chosen place
            BillingService -> Host --: ALREADY EXISTS
        end

        note right: location, \ntime, \nnumber of seats
    end

    group Update
        alt event exists
            BillingService -> Storage: update
            BillingService -> Host: OK

        else event doesn't exists
            BillingService -> Host --: NOT FOUND
        end

        note right: location, \ntime, \nnumber of seats
    end

    group Delete
        alt event exists
            BillingService -> Storage: delete
            BillingService -> Host: OK

        else event doesn't exists
            BillingService -> Host --: NOT FOUND
        end

        note right: location, \ntime, \nnumber of seats
    end

end

@enduml