"""host id for location

Revision ID: 0cce4e1e5ab5
Revises: 492383070f5e
Create Date: 2023-02-05 23:13:11.231123

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "0cce4e1e5ab5"
down_revision = "492383070f5e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "location", sa.Column("host_id", postgresql.UUID(as_uuid=True), nullable=True)
    )
    op.create_foreign_key(
        None, "location", "host", ["host_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "location", type_="foreignkey")
    op.drop_column("location", "host_id")
    # ### end Alembic commands ###
