"""event_seats_table_creation

Revision ID: 297c7abebaf4
Revises: d6a5b4ab4cb8
Create Date: 2023-01-25 01:45:51.617606

"""
import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op
from sqlalchemy.dialects import postgresql

from db.tables import EventSeatStatus

# revision identifiers, used by Alembic.
revision = "297c7abebaf4"
down_revision = "d6a5b4ab4cb8"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "event_seat",
        sa.Column("seat_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("event_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column(
            "status",
            sqlalchemy_utils.types.choice.ChoiceType(
                choices=EventSeatStatus, impl=sa.Integer()
            ),
            nullable=False,
        ),
        sa.Column("price", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(["event_id"], ["event.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["seat_id"], ["seat.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("seat_id", "event_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("event_seat")
    # ### end Alembic commands ###
