"""non-null constraints

Revision ID: 492383070f5e
Revises: 63a8a6df6832
Create Date: 2023-01-29 16:22:10.167267

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "492383070f5e"
down_revision = "63a8a6df6832"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "event",
        "notes",
        existing_type=sa.VARCHAR(),
        nullable=True,
        existing_comment="Extra information",
    )
    op.alter_column(
        "location",
        "name",
        existing_type=sa.VARCHAR(),
        nullable=False,
        existing_comment="location name",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "location",
        "name",
        existing_type=sa.VARCHAR(),
        nullable=True,
        existing_comment="location name",
    )
    op.alter_column(
        "event",
        "notes",
        existing_type=sa.VARCHAR(),
        nullable=False,
        existing_comment="Extra information",
    )
    # ### end Alembic commands ###
