"""user_tables_creation

Revision ID: 49fd2b72a875
Revises:
Create Date: 2023-01-25 00:29:44.431090

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "49fd2b72a875"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "guest",
        sa.Column("id", postgresql.UUID(), nullable=False),
        sa.Column("modified", sa.DateTime(), nullable=True),
        sa.Column("created", sa.DateTime(), nullable=True),
        sa.Column("rating", sa.Float(), nullable=True),
        sa.Column("events", sa.Integer(), nullable=True),
        sa.CheckConstraint("0 < rating AND rating < 10"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "host",
        sa.Column("id", postgresql.UUID(), nullable=False),
        sa.Column("modified", sa.DateTime(), nullable=True),
        sa.Column("created", sa.DateTime(), nullable=True),
        sa.Column("rating", sa.Float(), nullable=True),
        sa.Column("events", sa.Integer(), nullable=True),
        sa.CheckConstraint("0 < rating AND rating < 10"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("host")
    op.drop_table("guest")
    # ### end Alembic commands ###
