"""guest id is nullable for booking

Revision ID: 65c5ac7c6ea8
Revises: 99f0dc170acc
Create Date: 2023-02-06 02:03:49.631854

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "65c5ac7c6ea8"
down_revision = "99f0dc170acc"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "booking", sa.Column("guest_id", postgresql.UUID(as_uuid=True), nullable=True)
    )
    op.create_foreign_key(
        None, "booking", "guest", ["guest_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "booking", type_="foreignkey")
    op.drop_column("booking", "guest_id")
    # ### end Alembic commands ###
