"""place_table_creation

Revision ID: 6de0c62dba52
Revises: 49fd2b72a875
Create Date: 2023-01-25 00:40:08.668728

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "6de0c62dba52"
down_revision = "49fd2b72a875"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "place",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("modified", sa.DateTime(), nullable=True),
        sa.Column("created", sa.DateTime(), nullable=True),
        sa.Column("name", sa.String(), nullable=True, comment="Place name"),
        sa.Column("location", sa.String(), nullable=True, comment="Place location"),
        sa.Column("capacity", sa.Integer(), nullable=True, comment="Number of seats"),
        sa.Column("open", sa.Date(), nullable=True, comment="Place opening time"),
        sa.Column("close", sa.Date(), nullable=True, comment="Place closing time"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.alter_column(
        "guest",
        "events",
        existing_type=sa.INTEGER(),
        comment="number of events",
        existing_nullable=True,
    )
    op.alter_column(
        "host",
        "events",
        existing_type=sa.INTEGER(),
        comment="number of events",
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "host",
        "events",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="number of events",
        existing_nullable=True,
    )
    op.alter_column(
        "guest",
        "events",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="number of events",
        existing_nullable=True,
    )
    op.drop_table("place")
    # ### end Alembic commands ###
