"""guest id is nullable for booking

Revision ID: 99f0dc170acc
Revises: 0cce4e1e5ab5
Create Date: 2023-02-06 02:03:31.160102

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "99f0dc170acc"
down_revision = "0cce4e1e5ab5"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("booking_guest_id_fkey", "booking", type_="foreignkey")
    op.drop_column("booking", "guest_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "booking",
        sa.Column("guest_id", postgresql.UUID(), autoincrement=False, nullable=False),
    )
    op.create_foreign_key(
        "booking_guest_id_fkey",
        "booking",
        "guest",
        ["guest_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###
