"""seat_table_creation

Revision ID: 9f393f5dfa12
Revises: 6de0c62dba52
Create Date: 2023-01-25 00:53:36.017526

"""
import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op
from sqlalchemy.dialects import postgresql

from db.tables import SeatType

# revision identifiers, used by Alembic.
revision = "9f393f5dfa12"
down_revision = "6de0c62dba52"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "seat",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("modified", sa.DateTime(), nullable=True),
        sa.Column("created", sa.DateTime(), nullable=True),
        sa.Column("row", sa.Integer(), nullable=True),
        sa.Column("seat", sa.Integer(), nullable=True),
        sa.Column(
            "type",
            sqlalchemy_utils.types.choice.ChoiceType(SeatType, impl=sa.Integer()),
            nullable=False,
        ),
        sa.Column("place_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["place_id"],
            ["place.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("seat")
    # ### end Alembic commands ###
