"""event_guests_table_creation

Revision ID: acc474f29708
Revises: 297c7abebaf4
Create Date: 2023-01-25 01:56:52.220826

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "acc474f29708"
down_revision = "297c7abebaf4"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "guest_event",
        sa.Column("guest_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("event_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("host_score", sa.Integer(), nullable=True),
        sa.Column("event_score", sa.Integer(), nullable=True),
        sa.CheckConstraint("event_score > 0 AND event_score < 10"),
        sa.CheckConstraint("host_score > 0 AND host_score < 10"),
        sa.ForeignKeyConstraint(["event_id"], ["event.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["guest_id"], ["guest.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("guest_id", "event_id"),
    )
    op.drop_column("guest", "events")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "guest",
        sa.Column(
            "events",
            sa.INTEGER(),
            autoincrement=False,
            nullable=True,
            comment="number of events",
        ),
    )
    op.drop_table("guest_event")
    # ### end Alembic commands ###
