"""event_table_creation

Revision ID: cb3679df4648
Revises: 9f393f5dfa12
Create Date: 2023-01-25 01:09:07.245043

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "cb3679df4648"
down_revision = "9f393f5dfa12"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "event",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("modified", sa.DateTime(), nullable=True),
        sa.Column("created", sa.DateTime(), nullable=True),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("start", sa.DateTime(), nullable=True),
        sa.Column("duration", sa.Integer(), nullable=True, comment="Event duration, s"),
        sa.Column("movie_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("notes", sa.String(), nullable=True, comment="Extra information"),
        sa.Column(
            "participants",
            sa.Integer(),
            nullable=True,
            comment="Number of participants",
        ),
        sa.Column("place_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.ForeignKeyConstraint(["place_id"], ["place.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["host.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_constraint("seat_place_id_fkey", "seat", type_="foreignkey")
    op.create_foreign_key(
        None, "seat", "place", ["place_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "seat", type_="foreignkey")
    op.create_foreign_key("seat_place_id_fkey", "seat", "place", ["place_id"], ["id"])
    op.drop_table("event")
    # ### end Alembic commands ###
