"""empty message

Revision ID: d59188ebad8d
Revises: acc474f29708
Create Date: 2023-01-27 00:09:39.751405

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "d59188ebad8d"
down_revision = "acc474f29708"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "event", "start", existing_type=postgresql.TIMESTAMP(), nullable=False
    )
    op.alter_column(
        "event",
        "duration",
        existing_type=sa.INTEGER(),
        nullable=False,
        existing_comment="Event duration, s",
    )
    op.alter_column(
        "event",
        "notes",
        existing_type=sa.VARCHAR(),
        nullable=False,
        existing_comment="Extra information",
    )
    op.alter_column(
        "event",
        "participants",
        existing_type=sa.INTEGER(),
        nullable=False,
        existing_comment="Number of participants",
    )
    op.add_column(
        "guest",
        sa.Column(
            "events_num", sa.Integer(), nullable=True, comment="number of events"
        ),
    )
    op.drop_column("guest_event", "host_score")
    op.add_column(
        "host",
        sa.Column(
            "events_num", sa.Integer(), nullable=True, comment="number of events"
        ),
    )
    op.drop_column("host", "events")
    op.alter_column(
        "place",
        "location",
        existing_type=sa.VARCHAR(),
        nullable=False,
        existing_comment="Place location",
    )
    op.alter_column(
        "place",
        "capacity",
        existing_type=sa.INTEGER(),
        nullable=False,
        existing_comment="Number of seats",
    )
    op.create_unique_constraint(None, "place", ["name"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "place", type_="unique")
    op.alter_column(
        "place",
        "capacity",
        existing_type=sa.INTEGER(),
        nullable=True,
        existing_comment="Number of seats",
    )
    op.alter_column(
        "place",
        "location",
        existing_type=sa.VARCHAR(),
        nullable=True,
        existing_comment="Place location",
    )
    op.add_column(
        "host",
        sa.Column(
            "events",
            sa.INTEGER(),
            autoincrement=False,
            nullable=True,
            comment="number of events",
        ),
    )
    op.drop_column("host", "events_num")
    op.add_column(
        "guest_event",
        sa.Column("host_score", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.drop_column("guest", "events_num")
    op.alter_column(
        "event",
        "participants",
        existing_type=sa.INTEGER(),
        nullable=True,
        existing_comment="Number of participants",
    )
    op.alter_column(
        "event",
        "notes",
        existing_type=sa.VARCHAR(),
        nullable=True,
        existing_comment="Extra information",
    )
    op.alter_column(
        "event",
        "duration",
        existing_type=sa.INTEGER(),
        nullable=True,
        existing_comment="Event duration, s",
    )
    op.alter_column(
        "event", "start", existing_type=postgresql.TIMESTAMP(), nullable=True
    )
    # ### end Alembic commands ###
