"""purchased_movies_table_creation

Revision ID: d6a5b4ab4cb8
Revises: cb3679df4648
Create Date: 2023-01-25 01:13:49.618849

"""
# revision identifiers, used by Alembic.
revision = "d6a5b4ab4cb8"
down_revision = "cb3679df4648"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
